module.exports = {
  content: ["./views/**/*.tx", "./public/**/*.html"],
  theme: {
    extend: {},
  },
  plugins: [],
  safelist: [
    'hover:bg-cyan-500',
    'bg-cyan-600',
    'appearance-none',
    'h-full',
    'rounded-l',
    'border',
    'block',
    'appearance-none',
    'w-full',
    'bg-white',
    'border-gray-400',
    'text-gray-700',
    'py-2',
    'px-4',
    'pr-8',
    'leading-tight',
    'focus:outline-none',
    'focus:bg-white',
    'focus:border-gray-500',
  ],
}
