---
schema:
  procedures: {}
  tables:
    roles:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - role
          match_type: ''
          name: roles_role
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        role:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: role
          order: 2
          size:
            - 32
      indices: []
      name: roles
      options: []
      order: 1
    user_roles:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - user_id
            - role_id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - role_id
          match_type: ''
          name: user_roles_fk_role_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: roles
          type: FOREIGN KEY
        - deferrable: 1
          expression: ''
          fields:
            - user_id
          match_type: ''
          name: user_roles_fk_user_id
          on_delete: ''
          on_update: ''
          options: []
          reference_fields:
            - id
          reference_table: users
          type: FOREIGN KEY
      fields:
        role_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: role_id
          order: 2
          size:
            - 0
        user_id:
          data_type: integer
          default_value: ~
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: user_id
          order: 1
          size:
            - 0
      indices:
        - fields:
            - role_id
          name: user_roles_idx_role_id
          options: []
          type: NORMAL
        - fields:
            - user_id
          name: user_roles_idx_user_id
          options: []
          type: NORMAL
      name: user_roles
      options: []
      order: 3
    users:
      constraints:
        - deferrable: 1
          expression: ''
          fields:
            - id
          match_type: ''
          name: ''
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: PRIMARY KEY
        - deferrable: 1
          expression: ''
          fields:
            - email
          match_type: ''
          name: users_email
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
        - deferrable: 1
          expression: ''
          fields:
            - username
          match_type: ''
          name: users_username
          on_delete: ''
          on_update: ''
          options: []
          reference_fields: []
          reference_table: ''
          type: UNIQUE
      fields:
        deleted:
          data_type: tinyint
          default_value: 0
          is_nullable: 0
          is_primary_key: 0
          is_unique: 0
          name: deleted
          order: 6
          size:
            - 1
        email:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 1
          name: email
          order: 5
          size:
            - 255
        id:
          data_type: integer
          default_value: ~
          is_auto_increment: 1
          is_nullable: 0
          is_primary_key: 1
          is_unique: 0
          name: id
          order: 1
          size:
            - 0
        lastlogin:
          data_type: datetime
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: lastlogin
          order: 7
          size:
            - 0
        name:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: name
          order: 4
          size:
            - 128
        password:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: password
          order: 3
          size:
            - 64
        pw_changed:
          data_type: datetime
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: pw_changed
          order: 8
          size:
            - 0
        pw_reset_code:
          data_type: varchar
          default_value: ~
          is_nullable: 1
          is_primary_key: 0
          is_unique: 0
          name: pw_reset_code
          order: 9
          size:
            - 255
        username:
          data_type: varchar
          default_value: ~
          is_nullable: 0
          is_primary_key: 0
          is_unique: 1
          name: username
          order: 2
          size:
            - 32
      indices: []
      name: users
      options: []
      order: 2
  triggers: {}
  views: {}
translator:
  add_drop_table: 0
  filename: ~
  no_comments: 0
  parser_args:
    sources:
      - Role
      - User
      - UserRoles
  parser_type: SQL::Translator::Parser::DBIx::Class
  producer_args: {}
  producer_type: SQL::Translator::Producer::YAML
  show_warnings: 0
  trace: 0
  version: 1.62
